module.exports = {
  "_id": "55a34cf01d8e1e8ea7000006",
  "name_lowercase": "pj5_00001",
  "FQDN": "tnrich.pj5_00001",
  "sequence": "gacgtcttatgacaacttgacggctacatcattcactttttcttcacaaccggcacggaactcgctcgggctggccccggtgcattttttaaatacccgcgagaaatagagttgatcgtcaaaaccaacattgcgaccgacggtggcgataggcatccgggtggtgctcaaaagcagcttcgcctggctgatacgttggtcctcgcgccagcttaagacgctaatccctaactgctggcggaaaagatgtgacagacgcgacggcgacaagcaaacatgctgtgcgacgctggcgatatcaaaattgctgtctgccaggtgatcgctgatgtactgacaagcctcgcgtacccgattatccatcggtggatggagcgactcgttaatcgcttccatgcgccgcagtaacaattgctcaagcagatttatcgccagcagctccgaatagcgcccttccccttgcccggcgttaatgatttgcccaaacaggtcgctgaaatgcggctggtgcgcttcatccgggcgaaagaaccccgtattggcaaatattgacggccagttaagccattcatgccagtaggcgcgcggacgaaagtaaacccactggtgataccattcgcgagcctccggatgacgaccgtagtgatgaatctctcctggcgggaacagcaaaatatcacccggtcggcaaacaaattctcgtccctgatttttcaccaccccctgaccgcgaatggtgagattgagaatataacctttcattcccagcggtcggtcgataaaaaaatcgagataaccgttggcctcaatcggcgttaaacccgccaccagatgggcattaaacgagtatcccggcagcaggggatcattttgcgcttcagccatacttttcatactcccgccattcagagaagaaaccaattgtccatattgcatcagacattgccgtcactgcgtcttttactggctcttctcgctaaccaaaccggtaaccccgcttattaaaagcattctgtaacaaagcgggaccaaagccatgacaaaaacgcgtaacaaaagtgtctataatcacggcagaaaagtccacattgattatttgcacggcgtcacactttgctatgccatagcatttttatccataagattagcggattctacctgacgctttttatcgcaactctctactgtttctccatacccgtttttttgggaatttttaagaaggagatatacatatgagtaaaggagaagaacttttcactggagttgtcccaattcttgttgaattagatggtgatgttaatgggcacaaattttctgtcagtggagagggtgaaggtgatgcaacatacggaaaacttacccttaaatttatttgcactactggaaaactacctgttccatggccaacacttgtcactactttctcttatggtgttcaatgcttttcccgttatccggatcatatgaaacggcatgactttttcaagagtgccatgcccgaaggttatgtacaggaacgcactatatctttcaaagatgacgggaactacaagacgcgtgctgaagtcaagtttgaaggtgatacccttgttaatcgtatcgagttaaaaggtattgattttaaagaagatggaaacattctcggacacaaactcgaatacaactataactcacacaatgtatacatcacggcagacaaacaaaagaatggaatcaaagctaacttcaaaattcgccacaacattgaagatggatctgttcaactagcagaccattatcaacaaaatactccaattggcgatggccctgtccttttaccagacaaccattacctgtcgacacaatctgccctttcgaaagatcccaacgaaaagcgtgaccacatggtccttcttgagtttgtaactgctgctgggattacacatggcatggatgagctcggcggcggcggcagcaaggtctacggcaaggaacagtttttgcggatgcgccagagcatgttccccgatcgctaaatcgagtaaggatctccaggcatcaaataaaacgaaaggctcagtcgaaagactgggcctttcgttttatctgttgtttgtcggtgaacgctctctactagagtcacactggctcaccttcgggtgggcctttctgcgtttatacctagggtacgggttttgctgcccgcaaacgggctgttctggtgttgctagtttgttatcagaatcgcagatccggcttcagccggtttgccggctgaaagcgctatttcttccagaattgccatgattttttccccacgggaggcgtcactggctcccgtgttgtcggcagctttgattcgataagcagcatcgcctgtttcaggctgtctatgtgtgactgttgagctgtaacaagttgtctcaggtgttcaatttcatgttctagttgctttgttttactggtttcacctgttctattaggtgttacatgctgttcatctgttacattgtcgatctgttcatggtgaacagctttgaatgcaccaaaaactcgtaaaagctctgatgtatctatcttttttacaccgttttcatctgtgcatatggacagttttccctttgatatgtaacggtgaacagttgttctacttttgtttgttagtcttgatgcttcactgatagatacaagagccataagaacctcagatccttccgtatttagccagtatgttctctagtgtggttcgttgtttttgcgtgagccatgagaacgaaccattgagatcatacttactttgcatgtcactcaaaaattttgcctcaaaactggtgagctgaatttttgcagttaaagcatcgtgtagtgtttttcttagtccgttatgtaggtaggaatctgatgtaatggttgttggtattttgtcaccattcatttttatctggttgttctcaagttcggttacgagatccatttgtctatctagttcaacttggaaaatcaacgtatcagtcgggcggcctcgcttatcaaccaccaatttcatattgctgtaagtgtttaaatctttacttattggtttcaaaacccattggttaagccttttaaactcatggtagttattttcaagcattaacatgaacttaaattcatcaaggctaatctctatatttgccttgtgagttttcttttgtgttagttcttttaataaccactcataaatcctcatagagtatttgttttcaaaagacttaacatgttccagattatattttatgaatttttttaactggaaaagataaggcaatatctcttcactaaaaactaattctaatttttcgcttgagaacttggcatagtttgtccactggaaaatctcaaagcctttaaccaaaggattcctgatttccacagttctcgtcatcagctctctggttgctttagctaatacaccataagcattttccctactgatgttcatcatctgagcgtattggttataagtgaacgataccgtccgttctttccttgtagggttttcaatcgtggggttgagtagtgccacacagcataaaattagcttggtttcatgctccgttaagtcatagcgactaatcgctagttcatttgctttgaaaacaactaattcagacatacatctcaattggtctaggtgattttaatcactataccaattgagatgggctagtcaatgataattactagtccttttcccgggtgatctgggtatctgtaaattctgctagacctttgctggaaaacttgtaaattctgctagaccctctgtaaattccgctagacctttgtgtgttttttttgtttatattcaagtggttataatttatagaataaagaaagaataaaaaaagataaaaagaatagatcccagccctgtgtataactcactactttagtcagttccgcagtattacaaaaggatgtcgcaaacgctgtttgctcctctacaaaacagaccttaaaaccctaaaggcttaagtagcaccctcgcaagctcgggcaaatcgctgaatattccttttgtctccgaccatcaggcacctgagtcgctgtctttttcgtgacattcagttcgctgcgctcacggctctggcagtgaatgggggtaaatggcactacaggcgccttttatggattcatgcaaggaaactacccataatacaagaaaagcccgtcacgggcttctcagggcgttttatggcgggtctgctatgtggtgctatctgactttttgctgttcagcagttcctgccctctgattttccagtctgaccacttcggattatcccgtgacaggtcattcagactggctaatgcacccagtaaggcagcggtatcatcaacaggcttacccgtcttactgtccctagtgcttggattctcaccaataaaaaacgcccggcggcaaccgagcgttctgaacaaatccagatggagttctgaggtcattactggatctatcaacaggagtccaagcgagctcgatatcaaattacgccccgccctgccactcatcgcagtactgttgtaattcattaagcattctgccgacatggaagccatcacaaacggcatgatgaacctgaatcgccagcggcatcagcaccttgtcgccttgcgtataatatttgcccatggtgaaaacgggggcgaagaagttgtccatattggccacgtttaaatcaaaactggtgaaactcacccagggattggctgagacgaaaaacatattctcaataaaccctttagggaaataggccaggttttcaccgtaacacgccacatcttgcgaatatatgtgtagaaactgccggaaatcgtcgtggtattcactccagagcgatgaaaacgtttcagtttgctcatggaaaacggtgtaacaagggtgaacactatcccatatcaccagctcaccgtctttcattgccatacgaaattccggatgagcattcatcaggcgggcaagaatgtgaataaaggccggataaaacttgtgcttatttttctttacggtctttaaaaaggccgtaatatccagctgaacggtctggttataggtacattgagcaactgactgaaatgcctcaaaatgttctttacgatgccattgggatatatcaacggtggtatatccagtgatttttttctccattttagcttccttagctcctgaaaatctcgataactcaaaaaatacgcccggtagtgatcttatttcattatggtgaaagttggaacctcttacgtgccgatcaacgtctcattttcgccagatatc",
  "circular": true,
  "sequenceFileName": "pj5_00001.gb",
  "name": "pj5_00001",
  "sequenceFileFormat": "Genbank",
  "ve_metadata": "",
  "size": 5299,
  "dateModified": "2015-07-14T05:40:42.262Z",
  "dateCreated": "2015-07-13T05:30:24.986Z",
  "hash": "78cfd9da32ffb86af10057c8dd53ac30c607ed1d8991461a0a46cd14442935de",
  "description": "",
  "user_id": "54220bb6f54aa7432861e7dd",
  "features": [{
    "name": "CAP site",
    "type": "misc_binding",
    "id": "55a4a061f0c5b5000a8bfaf4",
    "start": 1114,
    "end": 1128,
    "strand": 1,
    "notes": []
  }, {
    "name": "Operator I2 and I1",
    "type": "protein_bind",
    "id": "55a4a061f0c5b5000a8bfaf5",
    "start": 1123,
    "end": 1162,
    "strand": 1,
    "notes": []
  }, {
    "name": "pBAD promoter",
    "type": "promoter",
    "id": "55a4a061f0c5b5000a8bfaf6",
    "start": 1160,
    "end": 1188,
    "strand": 1,
    "notes": []
  }, {
    "name": "RBS",
    "type": "RBS",
    "id": "55a4a061f0c5b5000a8bfaf7",
    "start": 1215,
    "end": 1235,
    "strand": 1,
    "notes": []
  }, {
    "name": "GFPuv",
    "type": "CDS",
    "id": "55a4a061f0c5b5000a8bfaf8",
    "start": 1235,
    "end": 2018,
    "strand": 1,
    "notes": [{
      "name": "vntifkey",
      "value": "4",
      "quoted": true
    }]
  }, {
    "name": "XhoI_silent_mutation",
    "type": "misc_feature",
    "id": "55a4a061f0c5b5000a8bfaf9",
    "start": 1660,
    "end": 1661,
    "strand": 1,
    "notes": []
  }, {
    "name": "BamHI_silent_mutation",
    "type": "misc_feature",
    "id": "55a4a061f0c5b5000a8bfafa",
    "start": 1759,
    "end": 1760,
    "strand": 1,
    "notes": []
  }, {
    "name": "signal_peptide",
    "type": "CDS",
    "id": "55a4a061f0c5b5000a8bfafb",
    "start": 1952,
    "end": 2015,
    "strand": 1,
    "notes": [{
      "name": "vntifkey",
      "value": "4",
      "quoted": true
    }]
  }, {
    "name": "dbl term",
    "type": "terminator",
    "id": "55a4a061f0c5b5000a8bfafc",
    "start": 2033,
    "end": 2162,
    "strand": 1,
    "notes": []
  }, {
    "name": "pSC101**",
    "type": "rep_origin",
    "id": "55a4a061f0c5b5000a8bfafd",
    "start": 2163,
    "end": 4392,
    "strand": -1,
    "notes": []
  }, {
    "name": "T0",
    "type": "terminator",
    "id": "55a4a061f0c5b5000a8bfafe",
    "start": 4392,
    "end": 4498,
    "strand": 1,
    "notes": []
  }, {
    "name": "CmR",
    "type": "misc_marker",
    "id": "55a4a061f0c5b5000a8bfaff",
    "start": 4513,
    "end": 5173,
    "strand": -1,
    "notes": []
  }],
  "extraLines": [],
  "__v": 4
}