import { setupOptions, setParamsIfNecessary } from "./utils/setupOptions";
import React from "react";
import { Callout } from "@blueprintjs/core";

import { SimpleCircularOrLinearView } from "../../src";
import renderToggle from "./utils/renderToggle";

const defaultState = {
  hoverPart: false,
  toggleSelection: false,
  noSequence: false,
  hideNameAndInfo: false,
  circular: false,
  changeSize: false,
  togglePartColor: false,
  toggleNoRedux: false
};

export default class SimpleCircularOrLinearViewDemo extends React.Component {
  constructor(props) {
    super(props);
    setupOptions({ that: this, defaultState, props });
  }
  componentDidUpdate() {
    setParamsIfNecessary({ that: this, defaultState });
  }
  render() {
    return (
      <div style={{ overflowY: "auto" }}>
        <Callout>
          This view is meant to be a helper for showing a simple (non-redux
          connected) circular or linear view!
        </Callout>
        <br></br>
        <br></br>
        <div style={{ display: "flex" }}>
          <div
            style={{
              width: "fit-content",
              borderRight: "1px solid lightgrey",
              marginRight: 10
            }}
          >
            {renderToggle({
              that: this,
              type: "hoverPart",
              label: "Toggle Part 1 Hover"
            })}

            {renderToggle({ that: this, type: "toggleSelection" })}
            {renderToggle({ that: this, type: "limitLengthTo50Bps" })}
            {renderToggle({ that: this, type: "superLongSequence" })}
            {renderToggle({
              that: this,
              type: "noSequence",
              label: "Don't pass .sequence, just .size",
              description:
                "You can pass sequenceData.noSequence=true if you don't want to have to pass the actual sequence. If you do this you must pass a sequenceData.size property"
            })}
            {renderToggle({ that: this, type: "hideNameAndInfo" })}
            {/* {renderToggle({ that: this, type: "showCutsites" })} */}
            {renderToggle({ that: this, type: "circular" })}
            {renderToggle({ that: this, type: "withAdditionalParts" })}
            {renderToggle({ that: this, type: "withCaretEnabled" })}
            {renderToggle({ that: this, type: "withChoosePreviewType" })}
            {renderToggle({ that: this, type: "minimalPreviewTypeBtns" })}
            {renderToggle({ that: this, type: "withFullscreen" })}
            {renderToggle({ that: this, type: "withVisibilityOptions" })}
            {renderToggle({ that: this, type: "withZoomLinearView" })}
            {renderToggle({ that: this, type: "withZoomCircularView" })}
            {renderToggle({
              that: this,
              type: "smallSlider",
              info: "Requires withZoomLinearView or withZoomCircularView to be enabled to see this one"
            })}
            {renderToggle({ that: this, type: "withDownload" })}
            {renderToggle({ that: this, type: "changeSize" })}
            {renderToggle({
              that: this,
              type: "partOverlapsSelf",
              description:
                "You can pass an overlapsSelf=true flag to parts to allow them wrap around the whole sequence and then some"
            })}
            {renderToggle({ that: this, type: "togglePartColor" })}
            {renderToggle({ that: this, type: "isOligo" })}
            {renderToggle({
              that: this,
              type: "toggleNoRedux",
              description:
                "Pass noRedux=true if you want to render this component in a redux-free environment. Note: passing hoveredIds will not work with noRedux=true"
            })}
            <br />
            <br />
          </div>
          <SimpleCircularOrLinearView
            {...{
              ...this.state,
              ...(this.state.toggleNoRedux && { noRedux: true }),
              ...(this.state.hideNameAndInfo && { hideName: true }),
              ...(this.state.hoverPart && { hoveredId: "fakeId1" }),
              ...(this.state.changeSize && { height: 500, width: 500 }),
              ...(this.state.toggleSelection && {
                selectionLayer: { start: 2, end: 30 }
              }),
              partClicked: () => {
                window.toastr.success("Part Clicked!");
              },
              partRightClicked: () => {
                window.toastr.success("Part Right Clicked!");
              },

              sequenceData: {
                sequence:
                  "GCCTGATGCGGTATTTTCTCCTTACGCATCTGTGCGGTATTTCACACCGCATACGTCAAAGCAACCATAGTACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCTTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCAGCTTATTTTTTGTATACTGTTTTGTGATAGCACGAAGTTTTTCCACGGTATCTTGTTAAAAATATATATTTGTGGCGGGCTTACCTACATCAAATTAATAAGAGACTAATTATAAACTAAACACACAAGCAAGCTACTTTAGGGTAAAAGTTTATAAATGCTTTTGACGTATAAACGTTGCTTGTATTTATTATTACAATTAAAGGTGGATAGAAAACCTAGAGACTAGTTAGAAACTAATCTCAGGTTTGCGTTAAACTAAATCAGAGCCCGAGAGGTTAACAGAACCTAGAAGGGGACTAGATATCCGGGTAGGGAAACAAAAAAAAAAAACAAGACAGCCACATATTAGGGAGACTAGTTAGAAGCTAGTTCCAGGACTAGGAAAATAAAAGACAATGATACCACAGTCTAGTTGACAACTAGATAGATTCTAGATTGAGGCCAAAGTCTCTGAGATCCAGGTTAGTTGCAACTAATACTAGTTAGTATCTAGTCTCCTATAACTCTGAAGCTAGAATAACTTACTACTATTATCCTCACCACTGTTCAGCTGCGCAAACGGAGTGATTGCAAGGTGTTCAGAGACTAGTTATTGACTAGTCAGTGACTAGCAATAACTAACAAGGTATTAACCTACCATGTCTGCCATCACCCTGCACTTCCTCGGGCTCAGCAGCCTTTTCCTCCTCATTTTCATGCTCATTTTCCTTGTTTAAGACTGTGACTAGTCAAAGACTAGTCCAGAACCACAAAGGAGAAATGTCTTACCACTTTCTTCATTGCTTGTCTCTTTTGCATTATCCATGTCTGCAACTAGTTAGAGTCTAGTTAGTGACTAGTCCGACGAGGACTTGCTTGTCTCCGGATTGTTGGAGGAACTCTCCAGGGCCTCAAGATCCACAACAGAGCCTTCTAGAAGACTGGTCAATAACTAGTTGGTCTTTGTCTGAGTCTGACTTACGAGGTTGCATACTCGCTCCCTTTGCCTCGTCAATCGATGAGAAAAAGCGCCAAAACTCGCAATATGGCTTTGAACCACACGGTGCTGAGACTAGTTAGAATCTAGTCCCAAACTAGCTTGGATAGCTTACCTTTGCCCTTTGCGTTGCGACAGGTCTTGCAGGGTATGGTTCCTTTCTCACCAGCTGATTTAGCTGCCTTGCTACCCTCACGGCGGATCTGCATAAAGAGTGGCTAGAGGTTATAAATTAGCACTGATCCTAGGTACGGGGCTGAATGTAACTTGCCTTTCCTTTCTCATCGCGCGGCAAGACAGGCTTGCTCAAATTCCTACCAGTCACAGGGGTATGCACGGCGTACGGACCACTTGAACTAGTCACAGATTAGTTAGCAACTAGTCTGCATTGAATGGCTGTACTTACGGGCCCTCGCCATTGTCCTGATCATTTCCAGCTTCACCCTCGTTGCTGCAAAGTAGTTAGTGACTAGTCAAGGACTAGTTGAAATGGGAGAAGAAACTCACGAATTCTCGACACCCTTAGTATTGTGGTCCTTGGACTTGGTGCTGCTATATATTAGCTAATACACTAGTTAGACTCACAGAAACTTACGCAGCTCGCTTGCGCTTCTTGGTAGGAGTCGGGGTTGGGAGAACAGTGCCTTCAAACAAGCCTTCATACCATGCTACTTGACTAGTCAGGGACTAGTCACCAAGTAATCTAGATAGGACTTGCCTTTGGCCTCCATCAGTTCCTTCATAGTGGGAGGTCCATTGTGCAATGTAAACTCCATGCCGTGGGAGTTCTTGTCCTTCAAGTGCTTGACCAATATGTTTCTGTTGGCAGAGGGAACCTGTCAACTAGTTAATAACTAGTCAGAAACTAGTATAGCAGTAGACTCACTGTACGCTTGAGGCATCCCTTCACTCGGCAGTAGACTTCATATGGATGGATATCAGGCACGCCATTGTCGTCCTGTGGACTAGTCAGTAACTAGGCTTAAAGCTAGTCGGGTCGGCTTACTATCTTGAAATCCGGCAGCGTAAGCTCCCCGTCCTTAACTGCCTCGAGATAGTGACAGTACTCTGGGGACTTTCGGAGATCGTTATCGCGAATGCTCGGCATACTAATCGTTGACTAGTCTTGGACTAGTCCCGAGCAAAAAGGATTGGAGGAGGAGGAGGAAGGTGAGAGTGAGACAAAGAGCGAAATAAGAGCTTCAAAGGCTATCTCTAAGCAGTATGAAGGTTAAGTATCTAGTTCTTGACTAGATTTAAAAGAGATTTCGACTAGTTATGTACCTGGAGTTTGGATATAGGAATGTGTTGTGGTAACGAAATGTAAGGGGGAGGAAAGAAAAAGTCGGTCAAGAGGTAACTCTAAGTCGGCCATTCCTTTTTGGGAGGCGCTAACCATAAACGGCATGGTCGACTTAGAGTTAGCTCAGGGAATTTAGGGAGTTATCTGCGACCACTGGACTCTCAGGCTTTCCATTGGGGTACTAACATAGCCATCAAATGCCGGCCCGTGTTTAATCTCCTCGAGATGGCTGGGCTCACATGCGTTCTACTCAAAAACTCTTATACCTAGGCCCTCTCCCAATCGTGTATGTTTGGACCTTCCTCTCTCACACTTTGGATAACATCAAGCATACCTGCAGATTTTGACCTAGTTAACAAGGCACATCATGCTATCACTTCCAACACTCTTGCTGAGCGCGTTCTGCCTTGCCTTTCTGGTTCTACGAAGTATCCAGTCCCGCCTGCAACGCCGCAGAAACGCCAAAAGGTGGGGTTGTCAACCGCCAGCTAGAGCTCCATCGGGATTCTTTGGCATTCCGCCGTTCCTCGGTGGTCGCAGATAACTCCCTAAATTCCCTGAGCTAACTCTAAGTCGACCATGCCGTTTATGGTTAGCGCCTCCCAAAAAGGAATGGCCGACTTAGAGTTACCTCTTGACCGACTTTTTCTTTCCTCCCCCTTACATTTCGTTACCACAACACATTCCTATATCCAAACTCCAGGTACATAACTAGTCGAAATCTCTTTTAAATCTAGTCAAGAACTAGATACTTAACCTTCATACTGCTTAGAGATAGCCTTTGAAGCTCTTATTTCGCTCTTTGTCTCACTCTCACCTTCCTCCTCCTCCTCCAATCCTTTTTGCTCGGGACTAGTCCAAGACTAGTCAACGATTAGTATGCCGAGCATTCGCGATAACGATCTCCGAAAGTCCCCAGAGTACTGTCACTATCTCGAGGCAGTTAAGGACGGGGAGCTTACGCTGCCGGATTTCAAGATAGTAAGCCGACCCGACTAGCTTTAAGCCTAGTTACTGACTAGTCCACAGGACGACAATGGCGTGCCTGATATCCATCCATATGAAGTCTACTGCCGAGTGAAGGGATGCCTCAAGCGTACAGTGAGTCTACTGCTATACTAGTTTCTGACTAGTTATTAACTAGTTGACAGGTTCCCTCTGCCAACAGAAACATATTGGTCAAGCACTTGAAGGACAAGAACTCCCACGGCATGGAGTTTACATTGCACAATGGACCTCCCACTATGAAGGAACTGATGGAGGCCAAAGGCAAGTCCTATCTAGATTACTTGGTGACTAGTCCCTGACTAGTCAAGTAGCATGGTATGAAGGCTTGTTTGAAGGCACTGTTCTCCCAACCCCGACTCCTACCAAGAAGCGCAAGCGAGCTGCGTAAGTTTCTGTGAGTCTAACTAGTGTATTAGCTAATATATAGCAGCACCAAGTCCAAGGACCACAATACTAAGGGTGTCGAGAATTCGTGAGTTTCTTCTCCCATTTCAACTAGTCCTTGACTAGTCACTAACTACTTTGCAGCAACGAGGGTGAAGCTGGAAATGATCAGGACAATGGCGAGGGCCCGTAAGTACAGCCATTCAATGCAGACTAGTTGCTAACTAATCTGTGACTAGTTCAAGTGGTCCGTACGCCGTGCATACCCCTGTGACTGGTAGGAATTTGAGCAAGCCTGTCTTGCCGCGCGATGAGAAAGGAAAGGCAAGTTACATTCAGCCCCGTACCTAGGATCAGTGCTAATTTATAACCTCTAGCCACTCTTTATGCAGATCCGCCGTGAGGGTAGCAAGGCAGCTAAATCAGCTGGTGAGAAAGGAACCATACCCTGCAAGACCTGTCGCAACGCAAAGGGCAAAGGTAAGCTATCCAAGCTAGTTTGGGACTAGATTCTAACTAGTCTCAGCACCGTGTGGTTCAAAGCCATATTGCGAGTTTTGGCGCTTTTTCTCATCGATTGACGAGGCAAAGGGAGCGAGTATGCAACCTCGTAAGTCAGACTCAGACAAAGACCAACTAGTTATTGACCAGTCTTCTAGAAGGCTCTGTTGTGGATCTTGAGGCCCTGGAGAGTTCCTCCAACAATCCGGAGACAAGCAAGTCCTCGTCGGACTAGTCACTAACTAGACTCTAACTAGTTGCAGACATGGATAATGCAAAAGAGACAAGCAATGAAGAAAGTGGTAAGACATTTCTCCTTTGTGGTTCTGGACTAGTCTTTGACTAGTCACAGTCTTAAACAAGGAAAATGAGCATGAAAATGAGGAGGAAAAGGCTGCTGAGCCCGAGGAAGTGCAGGGTGATGGCAGACATGGTAGGTTAATACCTTGTTAGTTATTGCTAGTCACTGACTAGTCAATAACTAGTCTCTGAACACCTTGCAATCACTCCGTTTGCGCAGCTGAACAGTGGTGAGGATAATAGTAGTAAGTTATTCTAGCTTCAGAGTTATAGGAGACTAGATACTAACTAGTATTAGTTGCAACTAACCTGGATCTCAGAGACTTTGGCCTCAATCTAGAATCTATCTAGTTGTCAACTAGACTGTGGTATCATTGTCTTTTATTTTCCTAGTCCTGGAACTAGCTTCTAACTAGTCTCCCTAATATGTGGCTGTCTTGTTTTTTTTTTTTGTTTCCCTACCCGGATATCTAGTCCCCTTCTAGGTTCTGTTAACCTCTCGGGCTCTGATTTAGTTTAACGCAAACCTGAGATTAGTTTCTAACTAGTCTCTAGGTTTTCTATCCACCTTTAATTGTAATAATAAATACAAGCAACGTTTATACGTCAAAAGCATTTATAAACTTTTACCCTAAAGTAGCTTGCTTGTGTGTTTAGTTTATAATTAGTCTCTTATTAATTTGATGTAGGTAAGCCCGCCACAAATATATATTTTTAACAAGATACCGTGGAAAAACTTCGTGCTATCACAAAACAGTATACAAAAAATAAGCTGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTTGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACTCTATCTCGGGCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGTCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTTTAACAAAATGGGGTGACGATGAGCCGCTCTTGCATCTTTGTTTGTATTATACTGTCTTTCTTGTTACACATAATTATTCTAGAATGCCCCACCGTTACATACGGGACACAGCCATTTACATATGCATGTGGATTACGAGCTAACGAGTTCATTCAAATCTCAGAACTATCACATAATCATCATTCCCCTATCGTCAAAGACCGTAAGACAAATCCGGTTCATGCACTGAACCCATTCGGGTAGTGAGTCATTTACTCAGCACACTCGCGCTGACGCTCGTCGAACACCTTCAATGCCTCCTCGGCAGCCTTGACACCACTGAGAACCATGGCACCGAAGGTAGGGCCCATGCGGTTAAAGCCATCAATTTCAGACAGCTCCATACCGCCGATTATCAAGCCCTTAGTAACCTCGCGGGTGTTCTTGACGATGGCATCCTGCGGCCGCCCAGAAAATTACGGGTATGTCCTCCACTGTGTTGAAGTCAGAAAAACAATCGATAATTTGAAGCTCATTAAAATGCCAGTTCCGTCGTCGCCGTTGCCCTAGGAGCTATTCCAGTGCTTAGCTTCATTCATGGATGTATCGTGACTGGCCTTCGGAAGGATGCCAAGGTCCCCTATCCGCACAGCTATGCGACCGTTGAGCAATGCAAGTCAAATGTGTGCATACCTGGTCTTTGGTTTGGTACACCGCTATGTGAAGATTATTAATGCTGAAGTCATGATACAGGCCAAAGCCGAGCAATTTAACTGCGCGCAGCGGGCCCACGCTAACTACCTCGAGAATATGCCTCAAACAATGCTCTTCACCCTCTTCGCGGGTCTGAAATACCCTCACCTGGCAACAGCAATTGGCGCTTCATGGCTGTTTTTCCGATCTCTCTACTTGTACGGCTATGTGTACTCGGGTAAGCCACAAGGCAAGGGCAGATTGCTGGGAGGTTTCTTCTGGTTTTCTCAAGGCGCTCTGTGGGCTCTGAGTGTGTTTGGTGTTGCCAAAGACATGATCTCTTACTGAGAGTTATTCTGTGTCTGACGAAATATGTTGTGTATATATATATATGTACGTTAAAAGTTCCGTGGAGTTACCAGTGATTGACCAATGTTTTATCTTCTACAGTTCTGCCTGTCTACCCCATTCTAGCTGTACCTGACTACAGAGTAGTTTAATTGTGGTTGACCCCACAGTCGGAGGCGGAGGAATACAGCACCGATGTGGCCTGTCTCCATCCAGATTGGCACGCAATTTTTACACGCGGAAAAGATCGAGATAGAGTACGACTTTAAATTTAGTCCCCGGCGGCTTCTATTTTAGAATATTTGAGATTTGATTCTCAAGCAATTGATTTGGTTGGGTCACCCTCAATTGGATAATATACCTCATTGCTCGGCTACTTCAACTCATCAATCACCGTCATACCCCGCATATAACCCTCCATTCCCACGATGTCGTCCAAGTCGCAATTGACTTACGGTGCTCGAGCCAGCAAGCACCCCAATCCTCTGGCAAAGAGACTTTTTGAGATTGCCGAAGCAAAGAAGACAAACGTTACCGTCTCTGCTGATGTGACGACAACCCGAGAACTCCTGGACCTCGCTGACCGTACGGAAGCTGTTGGATCCAATACATATGCCGTCTAGCAATGGACTAATCAACTTTTGATGATACAGGTCTCGGTCCCTACATCGCCGTCATCAAGACACACATCGACATCCTCACCGATTTCAGCGTCGACACTATCAATGGCCTGAATGTGCTGGCTCAAAAGCACAACTTTTTGATCTTCGAGGACCGCAAATTCATCGACATCGGCAATACCGTCCAGAAGCAATACCACGGCGGTGCTCTGAGGATCTCCGAATGGGCCCACATTATCAACTGCAGCGTTCTCCCTGGCGAGGGCATCGTCGAGGCTCTGGCCCAGACCGCATCTGCGCAAGACTTCCCCTATGGTCCTGAGAGAGGACTGTTGGTCCTGGCAGAGATGACCTCCAAAGGATCGCTGGCTACGGGCGAGTATACCAAGGCATCGGTTGACTACGCTCGCAAATACAAGAACTTCGTTATGGGTTTCGTGTCGACGCGGGCCCTGACGGAAGTGCAGTCGGATGTGTCTTCAGCCTCGGAGGATGAAGATTTCGTGGTCTTCACGACGGGTGTGAACCTCTCTTCCAAAGGAGATAAGCTTGGACAGCAATACCAGACTCCTGCATCGGCTATTGGACGCGGTGCCGACTTTATCATCGCCGGTCGAGGCATCTACGCTGCTCCCGACCCGGTTGAAGCTGCACAGCGGTACCAGAAAGAAGGCTGGGAAGCTTATATGGCCAGAGTATGCGGCAAGTCATGATTTCCTCTTGGAGCAAAAGTGTAGTGCCAGTACGAGTGTTGTGGAGGAAGGCTGCATACATTGTGCCTGTCATTAAACGATGAGCTCGTCCGTATTGGCCCCTGTAATGCCATGTTTTCCGCCCCCAATCGTCAAGGTTTTCCCTTTGTTAGATTCCTACCAGTCATCTAGCAAGTGAGGTAAGCTTTGCCAGAAACGCCAAGGCTTTATCTATGTAGTCGATAAGCAAAGTGGACTGATAGCTTAATATGGAAGGTCCCTCAGGACAAGTCGACCTGTGCAGAAGAGATAACAGCTTGGCATCACGCATCAGTGCCTCCTCTCAGACAGAATAAGTCGCCATAAGTTATCGACCGAACCTAGGTAGGGTATATTTGGTGACGACAATACCTCCCGACGATACCTGGATTAGACACCGTATGCCGCGAATTAACGCCTTCCGACCAAGTCCCTTTTGGTGATCGACACTTTAGGATCATCTCCTGCCAGTCGCCCAGACTGACGGTGTTATGGTGGCGCGCTATGGCTTTCCTAGCCGGTCAAGCTCCGTGCACTAGAGAGCGGAGAAGGAGGGGGAGTTGATAGGGAATGATATCTAGGTAGAGAAGTACTCCAACCAGAGATATGCGGATCAATGCTCCGGCAGTTGTTAGCATACCCCAACCTCGTTTAAGTATCCTCTTCTTCCATCCATCTTTATCATTATTTGTCTATGTGCATCCCTAGATCACGTCAATTATTTCGATAAATGGATACGTGCACTCGGGAATGCGTGATTGGCTCGTCTCGTGTTCTCAGTTCCTCATTCCCCCCCACGTTACATTGACAACGGAGTATTAGCCTATGGTCCTGTTCGATAAGCTTGCTCCATCGCCTCCACTACGTCAAGCGGAGTATCAGACATGAGCTCTACCCCAGATATCGCCTGCTTATCGCTGGTTGCTTTGTCATGCAAGTACAGATCACATCGGCAATTCTGATAACAGATGGTGCCATTGTCCCGTAATCAATTGCCCATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATAATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTACGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCATGATTACGAATTCATCACGTGCTATAAAAATAATTATAATTTAAATTTTTTAATATAAATATATAAATTAAAAATAGAAAGTAAAAAAAGAAATTAAAGAAAAAATAGTTTTTGTTTTCCGAAGATGTAAAAGACTCTAGGGGGATCGCCAACAAATACTACCTTTTATCTTGCTCTTCCTGCTCTCAGGTATTAATGCCGAATTGTTTCATCTTGTCTGTGTAGAAGACCACACACGAAAATCCTGTGATTTTACATTTTACTTATCGTTAATCGAATGTATATCTATTTAATCTGCTTTTCTTGTCTAATAAATATATATGTAAAGTACGCTTTTTGTTGAAATTTTTTAAACCTTTGTTTATTTTTTTTTCTTCATTCCGTAACTCTTCTACCTTCTTTATTTACTTTCTAAAATCCAAATACAAAACATAAAAATAAATAAACACAGAGTAAATTCCCAAATTATTCCATCATTAAAAGATACGAGGCGCGTGTAAGTTACGAATTCGAGCTCGGTACCCGGGATAACTTCGTATAATGTATGCTATACGAAGTTATGGGTAATAACTGATATAATTAAATTGAAGCTCTAATTTGTGAGTTTAGTATACATGCATTTACTTATAATACAGTTTTTTAGTTTTGCTGGCCGCATCTTCTCAAATATGCTTCCCAGCCTGCTTTTCTGTAACGTTCACCCTCTACCTTAGCATCCCTTCCCTTTGCAAATAGTCCTCTTCCAACAATAATAATGTCAGATCCTGTAGAGACCACATCATCCACGGTTCTATACTGTTGACCCAATGCGTCTCCCTTGTCATCTAAACCCACACCGGGTGTCATAATCAACCAATCGTAACCTTCATCTCTTCCACCCATGTCTCTTTGAGCAATAAAGCCGATAACAAAATCTTTGTCGCTCTTCGCAATGTCAACAGTACCCTTAGTATATTCTCCAGTAGATAGGGAGCCCTTGCATGACAATTCTGCTAACATCAAAAGGCCTCTAGGTTCCTTTGTTACTTCTTCTGCCGCCTGCTTCAAACCGCTAACAATACCTGGGCCCACCACACCGTGTGCATTCGTAATGTCTGCCCATTCTGCTATTCTGTATACACCCGCAGAGTACTGCAATTTGACTGTATTACCAATGTCAGCAAATTTTCTGTCTTCGAAGAGTAAAAAATTGTACTTGGCGGATAATGCCTTTAGCGGCTTAACTGTGCCCTCCATGGAAAAATCAGTCAAGATATCCACATGTGTTTTTAGTAAACAAATTTTGGGACCTAATGCTTCAACTAACTCCAGTAATTCCTTGGTGGTACGAACATCCAATGAAGCACACAAGTTTGTTTGCTTTTCGTGCATGATATTAAATAGCTTGGCAGCAACAGGACTAGGATGAGTAGCAGCACGTTCCTTATATGTAGCTTTCGACATGATTTATCTTCGTTTCCTGCAGGTTTTTGTTCTGTGCAGTTGGGTTAAGAATACTGGGCAATTTCATGTTTCTTCAACACTACATATGCGTATATATACCAATCTAAGTCTGTGCTCCTTCCTTCGTTCTTCCTTCTGTTCGGAGATTACCGAATCAAAAAAATTTCAAGGAAACCGAAATCAAAAAAAAGAATAAAAAAAAAATGATGAATTGAATTGAAAAGCGTGGTGCA",
                circular: true,
                name: "pKW-CA-URA3 - template",
                features: [
                  {
                    name: "URA3p",
                    type: "CDS",
                    start: 11452,
                    end: 12255,
                    strand: -1
                  },
                  {
                    name: "6Bo5HeX8YVvNHUsVIlU6sTMPobU.1415857363385.0",
                    type: "invisible_Parent",
                    start: 6192,
                    end: 18680,
                    strand: 1
                  },
                  {
                    name: "origin",
                    type: "origin",
                    arrowheadType: "NONE",
                    start: 2816,
                    end: 2815,
                    strand: -1
                  },
                  {
                    name: "CEN/ARS",
                    type: "rep_origin",
                    start: 10826,
                    end: 11317,
                    strand: 1
                  },
                  {
                    name: "NotI",
                    type: "restriction site",
                    arrowheadType: "NONE",
                    start: 6190,
                    end: 6197,
                    strand: -1
                  },
                  {
                    name: "MscI",
                    type: "restriction site",
                    arrowheadType: "NONE",
                    start: 8078,
                    end: 8083,
                    strand: -1
                  },
                  {
                    name: "Extracted region from pKW20088_pKW1903 (modified)",
                    type: "extracted region",
                    start: 2816,
                    end: 10812,
                    strand: 1
                  },
                  {
                    name: "Extracted region from pKW20088_pKW1903 (modified)",
                    type: "extracted region",
                    start: 0,
                    end: 2815,
                    strand: 1
                  },
                  {
                    name: "Extracted region from pBF-CA-ADH2-URA3@revised",
                    type: "extracted region",
                    start: 10813,
                    end: 12488,
                    strand: 1
                  },
                  {
                    name: "ptrA(1)",
                    type: "promoter",
                    locations: [
                      {
                        start: 9104,
                        end: 9117
                      },
                      {
                        start: 5766,
                        end: 6189
                      }
                    ],
                    start: 9104,
                    end: 6189,
                    strand: 1
                  },
                  {
                    name: "AMA1 ori for Aspergillus(1)",
                    type: "rep_origin",
                    start: 199,
                    end: 2815,
                    strand: 1
                  },
                  {
                    name: "AMA1 ori for Aspergillus",
                    type: "rep_origin",
                    start: 2816,
                    end: 5092,
                    strand: 1
                  },
                  {
                    name: "PyrG(A.fumigatus)_1kb_downstream",
                    type: "terminator",
                    start: 8104,
                    end: 9103,
                    strand: 1
                  },
                  {
                    name: "PyrG(A.fumigatus)_1kb_upstream",
                    type: "promoter",
                    start: 6199,
                    end: 7198,
                    strand: 1
                  },
                  {
                    name: "Afu2g08360(PyrG)",
                    type: "CDS",
                    start: 7199,
                    end: 8103,
                    strand: 1
                  },
                  {
                    name: "AMA1 ori for Aspergillus(2)",
                    type: "rep_origin",
                    start: 5093,
                    end: 5446,
                    strand: 1
                  },
                  {
                    name: "ptrA",
                    type: "misc_feature",
                    arrowheadType: "NONE",
                    start: 6198,
                    end: 6198,
                    strand: -1
                  },
                  {
                    name: "EagI",
                    type: "misc_feature",
                    arrowheadType: "NONE",
                    start: 6198,
                    end: 6198,
                    strand: -1
                  },
                  {
                    name: "URA3 prom",
                    type: "Promoter",
                    start: 12257,
                    end: 12482,
                    strand: -1
                  },
                  {
                    name: "amp marker",
                    type: "CDS",
                    start: 9137,
                    end: 9997,
                    strand: 1
                  },
                  {
                    name: "pBR322 origin",
                    type: "Origin of Replication",
                    start: 10152,
                    end: 10771,
                    strand: 1
                  }
                ]
              }
            }}
          />
        </div>

        <br />
        <code>
          <h3> Usage: </h3>
          <pre>
            {`<SimpleCircularOrLinearView
  {...{
    ...(this.state.hideNameAndInfo && { hideName: true }),
    ...(this.state.hoverPart && { hoveredId: "fakeId1" }),
    ...(this.state.changeSize && { height: 500, width: 500 }),

    sequenceData: {
      name: "Test Seq",
      circular: this.state.circular, //toggle to true to change this!
      parts: [
        {
          name: "Part 1",
          id: "fakeId1",
          start: 10,
          end: 20
        },
        {
          name: "Part 2",
          id: "fakeId4",
          start: 25,
          end: 30
        }
      ],
      sequence:
        "GGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacaccccccGGGAAAagagagtgagagagtagagagagaccacacccccc"
    }
  }}
/>`
              .split("\n")
              .map((l, i) => (
                <div key={i}>{l}</div>
              ))}
          </pre>
        </code>
      </div>
    );
  }
}
